services:
  - repo_name: "fake-api-1"
    service_name: "FakeRest"
    swagger_url: "https://fakerestapi.azurewebsites.net/swagger/v1/swagger.json"
  - repo_name: "original-api-1"
    service_name: "OriginalRest"
    swagger_url: "https://fakerestapi.azurewebsites.net/swagger/v1/swagger.json"
  - repo_name: "original-api-1"
    service_name: "OriginalRest"
    swagger_url: "https://fakerestapi.azurewebsites.net/swagger/v1/swagger.json"
